const crypto = require('crypto');
const ShareableHash = require('../models/ShareableHash');

// 1. Generate a new Public Hash / QR Code data
exports.createHash = async (req, res) => {
    try {
        const { actions } = req.body;

        if (!actions || !Array.isArray(actions) || actions.length === 0) {
            return res.status(400).json({ 
                success: false, 
                message: "Please provide an array of actions (e.g., ['ALL'] or ['SET_GOALS'])." 
            });
        }

        // Generate a 32-byte secure random hex string (64 characters long)
        const hashId = crypto.randomBytes(32).toString('hex');

        const newHash = new ShareableHash({
            hashId,
            userId: req.user.id, // Extracted from requireJWT middleware
            actions,
            status: 'ACTIVE'
        });

        await newHash.save();

        res.status(201).json({
            success: true,
            message: "QR Hash generated successfully.",
            data: newHash
        });

    } catch (error) {
        console.error("🔥 Error creating hash:", error);
        res.status(500).json({ success: false, message: "Server error generating hash." });
    }
};

// 2. Get all hashes generated by the logged-in user
exports.getAllHashes = async (req, res) => {
    try {
        // Fetch all hashes for this user, sorted by newest first
        const hashes = await ShareableHash.find({ userId: req.user.id })
                                          .sort({ createdAt: -1 });

        res.status(200).json({
            success: true,
            data: hashes
        });

    } catch (error) {
        console.error("🔥 Error fetching hashes:", error);
        res.status(500).json({ success: false, message: "Server error fetching hashes." });
    }
};

// 3. Update Hash Status (Active / Unactive)
exports.updateHashStatus = async (req, res) => {
    try {
        const { hashId } = req.params;
        const { status } = req.body;

        if (!['ACTIVE', 'UNACTIVE'].includes(status)) {
            return res.status(400).json({ 
                success: false, 
                message: "Invalid status. Must be ACTIVE or UNACTIVE." 
            });
        }

        // Find by hashId AND userId to ensure the user actually owns this hash
        const updatedHash = await ShareableHash.findOneAndUpdate(
            { hashId, userId: req.user.id },
            { status },
            { new: true } // Returns the updated document
        );

        if (!updatedHash) {
            return res.status(404).json({ 
                success: false, 
                message: "Hash not found or you do not have permission to modify it." 
            });
        }

        res.status(200).json({
            success: true,
            message: `Hash status updated to ${status}.`,
            data: updatedHash
        });

    } catch (error) {
        console.error("🔥 Error updating hash status:", error);
        res.status(500).json({ success: false, message: "Server error updating status." });
    }
};

// 4. Completely Delete a Hash
exports.deleteHash = async (req, res) => {
    try {
        const { hashId } = req.params;

        const deletedHash = await ShareableHash.findOneAndDelete({ 
            hashId, 
            userId: req.user.id 
        });

        if (!deletedHash) {
            return res.status(404).json({ 
                success: false, 
                message: "Hash not found or you do not have permission to delete it." 
            });
        }

        res.status(200).json({
            success: true,
            message: "Hash deleted successfully."
        });

    } catch (error) {
        console.error("🔥 Error deleting hash:", error);
        res.status(500).json({ success: false, message: "Server error deleting hash." });
    }
};

// 5. Update Hash Permissions (Actions)
exports.updateHashActions = async (req, res) => {
    try {
        const { hashId } = req.params;
        const { actions } = req.body;

        if (!actions || !Array.isArray(actions) || actions.length === 0) {
            return res.status(400).json({ 
                success: false, 
                message: "Please provide an array of actions." 
            });
        }

        const updatedHash = await ShareableHash.findOneAndUpdate(
            { hashId, userId: req.user.id },
            { actions },
            { new: true } // Returns the updated document
        );

        if (!updatedHash) {
            return res.status(404).json({ 
                success: false, 
                message: "Hash not found or you do not have permission to modify it." 
            });
        }

        res.status(200).json({
            success: true,
            message: "Link permissions updated successfully.",
            data: updatedHash
        });

    } catch (error) {
        console.error("🔥 Error updating hash actions:", error);
        res.status(500).json({ success: false, message: "Server error updating permissions." });
    }
};