const { fetchGoogleRoute } = require('../services/googleRoutesHelper');

exports.calculateRoute = async (req, res) => {
    try {
        const { origin, destination, mapType } = req.body;

        if (!origin || !destination) {
            return res.status(400).json({ success: false, dataType: 'ERROR', message: "Origin and destination are required." });
        }

        const routeData = await fetchGoogleRoute(req.body);

        let dataType = 'UNKNOWN';
        if (!routeData.routes || routeData.routes.length === 0) {
            dataType = 'NO_ROUTE_FOUND';
        } else if (routeData.routes.length === 1) {
            dataType = 'SUCCESS_SINGLE_ROUTE';
        } else if (routeData.routes.length > 1) {
            dataType = 'SUCCESS_MULTIPLE_ROUTES';
        }

        if (routeData.fallbackInfo) {
            dataType = 'SUCCESS_FALLBACK_ROUTE';
        }

        res.status(200).json({
            success: true,
            dataType: dataType,
            clientMapType: mapType || 'DEFAULT',
            data: routeData
        });

    } catch (error) {
        // Forward the exact error string generated by the helper
        res.status(500).json({
            success: false,
            dataType: 'ERROR',
            message: error.message
        });
    }
};